name: baiki2
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^3.0.3
  google_fonts: ^4.0.5
  beamer: ^1.5.3
  url_strategy: ^0.2.0
  url_launcher: ^6.1.8
  sliver_tools: ^0.2.8
  google_nav_bar: ^5.0.6
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  flutter_bloc: ^8.1.3
  auto_route: ^7.2.0
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  rxdart: ^0.27.7
  bloc: ^8.1.2
  dio: ^5.1.2
  eva_icons_flutter: ^3.1.0
  flutter_svg: ^2.0.6
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0
  http: ^1.0.0
  http_mock_adapter: ^0.4.4
  introduction_screen: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  auto_route_generator: ^7.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

